### ISSUE TITLE
Replace selection with result

### ISSUE THREAD

**Issue by tobia** [andrewcarreiro/vscode-calculate#1]
Is there an alternative command that replaces the selection with the result, instead of adding "=result"?

The Sublime calc extension had it and it was very useful to quickly calculate a large number of selections.

**Comment by andrewcarreiro** [comment]
Great suggestion. I've published a new version that includes a "Calculate and Replace" option - https://github.com/andrewcarreiro/vscode-calculate/commit/4917e39687a684a0e54ec1131093c65d5ee007db
