### ISSUE TITLE
Slow Startup Activation

### ISSUE THREAD

**Issue by faustinoaq** [andrewcarreiro/vscode-calculate#4]
- Extension Name: calculate
- Extension Version: 1.2.0
- OS Version: Linux x64 4.14.14-1-MANJARO
- VSCode version: 1.19.0

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 736,
		"activateCallTime": 0,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

Currently this extension is taking almost 1 second to load, is the slowest extension in my vscode:

![screenshot_20180121_132309](https://user-images.githubusercontent.com/3067335/35197522-3ba00fba-feae-11e7-8cb2-8b61b441c075.png)

I made this issue using the new VSCode profiling feature 👍

**Comment by andrewcarreiro** [comment]
Thanks for bringing this up. I don't have any immediate ideas around what might be the cause, but I'll take a look in the next few days. Let me know if you have any suggestions.

**Comment by faustinoaq** [comment]
@andrewcarreiro You can try to reproduce it and share your _Running extensions_ 👍 

![screenshot_20180124_131443](https://user-images.githubusercontent.com/3067335/35349290-8bf06274-0108-11e8-88a1-79a7441ae0c1.png)

_^ Calculate is still the slowest extension by far, Settings Sync by @shanalikhan is also some slow_ 😅

**Comment by shanalikhan** [comment]
😄 
Always looking to improve.

https://github.com/shanalikhan/code-settings-sync/issues/472

**Comment by andrewcarreiro** [comment]
Hm, it looks like the [majority of the startup time](https://docs.google.com/spreadsheets/d/1tG-aunPdDUPvpe5AjQQ2siJhzyUaoCdYHnv3Fwh3FmU/edit#gid=0) is being created by loading the full Math.js.

We could consider a different library, but I would be concerned about breaking things for users. If this becomes enough of a pain point, we could consider allowing users to decide through configuration which library they'd want.

For future people, please 👍 up the top comment if startup time becomes something intolerable.

**Comment by gabrielmoreira** [comment]
Why not use ["Performance - Extension Activation"](https://code.visualstudio.com/docs/extensionAPI/patterns-and-principles#_performance-extension-activation) on ```package.json```?
```json
"activationEvents": [
    "onCommand:extension.calculate",
    "onCommand:extension.calculateReplace"
]
```

My startup activation time:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 2128,
		"activateCallTime": 0,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```
